server:
   port: 8091
spring:
  datasource: 
    url: jdbc:mysql://localhost:3309/db_ms_productos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: userdev
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: create
    show-sql: true  
    
# Server Registry Client
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka/
   instance:
      instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}  	
      prefer-ip-address: true

#spring:
#  datasource: 
#    url: jdbc:mysql://mysql_productos_dev:3306/db_ms_productos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: userdev
#    password: Test@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      initializationFailTimeout: 0
#  jpa: 
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate: 
#      ddl-auto: update
#    show-sql: true
#
## Server Registry Client
#eureka:
#   client:
#      register-with-eureka: true
#      fetch-registry: true
#      serviceUrl:
#         defaultZone: http://eureka-server:8889/eureka
#   instance:
#      instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}  	
#      prefer-ip-address: true
